#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1

cleanCase

# Remove decomposeParDict
rm -f system/decomposeParDict

rm *.txt
rm slurm*

rm system/initialConditions
rm Mycek_03TI/0.org/include/initialConditions


# ----------------------------------------------------------------- end-of-file
