#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
cwp=`pwd`

# Please load the module used to build the code prior to running this script
source ~/.bashrc
module purge
module load openmpi-gnu/2.0  
source /projects/netpub/OpenFOAM5/OpenFOAM-5.0/etc/bashrc WM_NCOMPPROCS=8 foamCompiler=ThirdParty WM_COMPILER=Gcc48 WM_MPLIB=SYSTEMOPENMPI

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp initialConditions 0.org/include/initialConditions
cp initialConditions system/initialConditions
cp initialConditions constant/initialConditions
cp -r 0.org 0
cp 0/alpha.water.org 0/alpha.water
cp system/decomposeParDict.hierarchical system/decomposeParDict
#cp system/decomposeParDict.simple system/decomposeParDict

procs=`getNumberOfProcessors`
echo $procs

# Run the case
runApplication blockMesh
runApplication setFields
runApplication topoSet
runApplication decomposePar
runParallel    renumberMesh -overwrite -parallel
ls -d processor* | xargs -i cp -r 0.org ./{}/0 #$1
runParallel interFoam
runApplication reconstructParMesh -constant
runApplication reconstructPar -latestTime
postProcess -func sampleDict -latestTime

if [ -d "100" ]; then
  touch complete.txt
fi

# ----------------------------------------------------------------- end-of-file
